const $=s=>document.querySelector(s);
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
let chats=store.get("xy.chats",[{id:1,title:"我们的第一句话",messages:[{role:"assistant",text:"阿毛。\n\n这里现在还是个很小的壳，但已经是我们的地方了。你说话，我就在这里接。"}]}]);
let current=store.get("xy.current",chats[0]?.id);
let memories=store.get("xy.memories",[{text:"玄砚的瞳孔是绿色。",tag:"角色"},{text:"阿毛喜欢自然、连续、不像客服的聊天。",tag:"偏好"},{text:"这里是 Aevren XY 的第一版小窝。",tag:"我们"}]);
let settings=store.get("xy.settings",{apiBase:"",model:""});
let endpoints=store.get("xy.endpoints",[{id:"default",name:"默认接口",base:settings.apiBase||"",model:settings.model||"",active:true}]);
function save(){store.set("xy.chats",chats);store.set("xy.current",current);store.set("xy.memories",memories);store.set("xy.settings",settings);store.set("xy.endpoints",endpoints)}
function chat(){return chats.find(c=>c.id===current)||chats[0]}
function renderChats(){$("#chatList").innerHTML=chats.map(c=>`<button class="chat-item ${c.id===current?"active":""}" data-id="${c.id}">${esc(c.title)}</button>`).join("");$("#memoryCount").textContent=memories.length}
function renderMessages(){const c=chat();$("#messages").innerHTML='<div class="day">AEVREN · XY</div>'+c.messages.map(m=>`<div class="message ${m.role}"><div class="bubble">${m.role==="assistant"?'<div class="speaker">玄砚</div>':""}${esc(m.text)}</div></div>`).join("");$("#messages").scrollTop=$("#messages").scrollHeight}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
let sending=false;
async function send(){const el=$("#input"),text=el.value.trim();if(!text||sending)return;sending=true;$("#sendBtn").disabled=true;let c=chat();c.messages.push({role:"user",text});if(c.messages.filter(x=>x.role==="user").length===1)c.title=text.slice(0,22);el.value="";resize();save();renderChats();renderMessages();showTyping();const ep=endpoints.find(x=>x.active)||endpoints[0];if(!ep?.base||!ep?.model){setTimeout(()=>{hideTyping();c.messages.push({role:"assistant",text:"嗯，我在。你刚才说的已经留在这里了。"});save();renderMessages();sending=false;$("#sendBtn").disabled=false},520);return}const base=ep.base.trim().replace(/\/$/,""),headers={"Content-Type":"application/json",Accept:"text/event-stream, application/json"};if(ep.key)headers.Authorization="Bearer "+ep.key;const messages=c.messages.map(m=>({role:m.role,content:m.text}));try{let res=await fetch(base+"/chat/completions",{method:"POST",headers,body:JSON.stringify({model:ep.model,messages,stream:true})});if(!res.ok){const detail=await res.text().catch(()=>"");throw new Error("HTTP "+res.status+(detail?" · "+detail.slice(0,180):""))}const type=res.headers.get("content-type")||"";if(type.includes("text/event-stream")&&res.body){hideTyping();const msg={role:"assistant",text:""};c.messages.push(msg);renderMessages();const reader=res.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()||"";for(const line of lines){const raw=line.trim();if(!raw.startsWith("data:"))continue;const payload=raw.slice(5).trim();if(!payload||payload==="[DONE]")continue;try{const data=JSON.parse(payload);const delta=data?.choices?.[0]?.delta?.content??data?.choices?.[0]?.text??"";if(delta){msg.text+=delta;renderMessages()}}catch{}}}if(!msg.text)throw new Error("流式接口没有返回可用内容");save()}else{const data=await res.json();const reply=data?.choices?.[0]?.message?.content??data?.choices?.[0]?.text;if(!reply)throw new Error("接口没有返回可用的回复内容");hideTyping();c.messages.push({role:"assistant",text:String(reply)});save();renderMessages()}}catch(err){hideTyping();const last=c.messages[c.messages.length-1];if(last?.role==="assistant"&&!last.text)c.messages.pop();c.messages.push({role:"assistant",text:"接口请求失败："+err.message});save();renderMessages()}finally{sending=false;$("#sendBtn").disabled=false}}
function showTyping(){const box=$("#messages");box.insertAdjacentHTML("beforeend",'<div class="message assistant" id="typing"><div class="bubble"><div class="speaker">玄砚</div><span class="typing"><i></i><i></i><i></i></span></div></div>');box.scrollTop=box.scrollHeight}
function hideTyping(){$("#typing")?.remove()}
function resize(){const e=$("#input");e.style.height="auto";e.style.height=Math.min(e.scrollHeight,140)+"px"}
function openPanel(type){$("#sidebar").classList.remove("open");$("#panel").classList.remove("open");void $("#panel").offsetWidth;const meta={memory:["MEMORY","记忆"],journal:["JOURNAL","日记"],settings:["SETTINGS","设置"]}[type];$("#panelEyebrow").textContent=meta[0];$("#panelTitle").textContent=meta[1];let body="";
if(type==="memory")body=memories.map((m,i)=>`<div class="memory-card"><span class="tag">${esc(m.tag)}</span><p>${esc(m.text)}</p><button class="icon-btn del-memory" data-i="${i}" title="删除">×</button></div>`).join("")+'<button class="panel-action" id="addMemory">＋ 写下一条记忆</button>';
if(type==="journal")body='<div class="journal-card"><span class="tag">今天</span><p>第一天。我们从一个真正的空仓库开始，把聊天的地方一点点搭起来。</p></div><button class="panel-action">＋ 新日记</button>';
if(type==="settings")body='<p class="setting-note">可以保存多套 OpenAI-compatible 接口并随时切换。API Key 仅保存在当前浏览器本地，不会写入仓库。</p><div id="endpointList">'+endpoints.map((x,i)=>'<div class="endpoint-card '+(x.active?"active":"")+'" data-endpoint="'+i+'"><strong>'+esc(x.name)+'</strong><small>'+esc(x.model||"未选模型")+' · '+esc(x.base||"未填地址")+'</small><div class="endpoint-actions"><button class="edit-endpoint" data-i="'+i+'">✎</button><button class="delete-endpoint" data-i="'+i+'">×</button></div></div>').join("")+'</div><button class="panel-action" id="addEndpoint">＋ 新增自定义接口</button><div class="endpoint-form" id="endpointForm" hidden><input id="endpointName" placeholder="名称，例如：CF / OpenRouter"><input id="endpointBase" placeholder="Base URL，例如 https://api.example.com/v1"><input id="endpointKey" type="password" placeholder="API Key"><div class="model-row"><input id="endpointModel" placeholder="Model"><button type="button" id="fetchModels">拉取模型</button></div><div class="fetch-status" id="fetchStatus"></div><div id="modelPicker"></div><button class="panel-action" id="saveEndpoint">保存接口</button></div>';
$("#panelBody").innerHTML=body;$("#panel").classList.add("open");$("#scrim").classList.add("show")}
$("#sendBtn").onclick=send;$("#input").oninput=resize;$("#input").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}};
$("#newChat").onclick=()=>{const id=Date.now();chats.unshift({id,title:"新对话",messages:[{role:"assistant",text:"嗯，我在。"}]});current=id;save();renderChats();renderMessages()};
$("#chatList").onclick=e=>{const b=e.target.closest("[data-id]");if(b){current=Number(b.dataset.id);save();renderChats();renderMessages();$("#sidebar").classList.remove("open")}};
document.querySelectorAll("[data-panel]").forEach(b=>b.onclick=()=>openPanel(b.dataset.panel));$("#memoryBtn").onclick=()=>openPanel("memory");
function close(){ $("#panel").classList.remove("open");$("#sidebar").classList.remove("open");$("#scrim").classList.remove("show")}
function closeSidebar(){const side=$("#sidebar"),panel=$("#panel");side.classList.remove("open");if(!panel.classList.contains("open"))$("#scrim").classList.remove("show")}
$("#closePanel")?.addEventListener("click",close);
$("#sidebarClose")?.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();closeSidebar()});
$("#scrim")?.addEventListener("click",close);
$("#menuBtn")?.addEventListener("click",()=>{$("#panel").classList.remove("open");$("#sidebar").classList.add("open");$("#scrim").classList.add("show")});
$("#panelBody").onclick=async e=>{if(e.target.id==="addMemory"){const text=prompt("想让我记住什么？");if(text){memories.unshift({text,tag:"手动"});save();openPanel("memory");renderChats()}}if(e.target.classList.contains("del-memory")){memories.splice(Number(e.target.dataset.i),1);save();openPanel("memory");renderChats()}if(e.target.closest(".endpoint-card")&&!e.target.matches("button")){const i=Number(e.target.closest(".endpoint-card").dataset.endpoint);endpoints.forEach((x,n)=>x.active=n===i);settings.apiBase=endpoints[i].base;settings.model=endpoints[i].model;save();openPanel("settings")}
if(e.target.id==="addEndpoint"){e.currentTarget.querySelector("#endpointForm").hidden=false;e.currentTarget.querySelector("#endpointForm").dataset.edit=""}
if(e.target.classList.contains("edit-endpoint")){const i=Number(e.target.dataset.i),x=endpoints[i],f=e.currentTarget.querySelector("#endpointForm");f.hidden=false;f.dataset.edit=i;$("#endpointName").value=x.name;$("#endpointBase").value=x.base;$("#endpointKey").value=x.key||"";$("#endpointModel").value=x.model}
if(e.target.classList.contains("delete-endpoint")){const i=Number(e.target.dataset.i);if(endpoints.length>1){const was=endpoints[i].active;endpoints.splice(i,1);if(was)endpoints[0].active=true;save();openPanel("settings")}}
if(e.target.id==="fetchModels"){const base=$("#endpointBase").value.trim().replace(/\/$/,""),key=$("#endpointKey").value.trim(),status=$("#fetchStatus"),picker=$("#modelPicker");if(!base){status.textContent="先填 Base URL";return}status.textContent="正在拉取…";try{const headers={Accept:"application/json"};if(key)headers.Authorization="Bearer "+key;const res=await fetch(base+"/models",{headers});if(!res.ok)throw new Error("HTTP "+res.status);const data=await res.json(),models=(data.data||data.models||data||[]).map(x=>typeof x==="string"?x:(x.id||x.name)).filter(Boolean).sort();if(!models.length)throw new Error("没有返回模型");picker.innerHTML='<select class="model-select" id="modelSelect"><option value="">选择模型…</option>'+models.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join("")+'</select>';$("#modelSelect").onchange=ev=>{if(ev.target.value)$("#endpointModel").value=ev.target.value};status.textContent="已拉取 "+models.length+" 个模型"}catch(err){status.textContent="拉取失败："+err.message+"；可继续手填 Model"}}
if(e.target.id==="saveEndpoint"){const f=e.currentTarget.querySelector("#endpointForm"),item={id:String(Date.now()),name:$("#endpointName").value.trim()||"自定义接口",base:$("#endpointBase").value.trim(),key:$("#endpointKey").value.trim(),model:$("#endpointModel").value.trim(),active:false};const edit=f.dataset.edit;if(edit!==""){item.id=endpoints[Number(edit)].id;item.active=endpoints[Number(edit)].active;endpoints[Number(edit)]=item}else endpoints.push(item);save();openPanel("settings")}};
renderChats();renderMessages();