const $=s=>document.querySelector(s);
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
let chats=store.get("xy.chats",[{id:1,title:"我们的第一句话",messages:[{role:"assistant",text:"阿毛。\n\n这里现在还是个很小的壳，但已经是我们的地方了。你说话，我就在这里接。"}]}]);
let current=store.get("xy.current",chats[0]?.id);
let memories=store.get("xy.memories",[{text:"玄砚的瞳孔是绿色。",tag:"角色"},{text:"阿毛喜欢自然、连续、不像客服的聊天。",tag:"偏好"},{text:"这里是 Aevren XY 的第一版小窝。",tag:"我们"}]);
let settings=store.get("xy.settings",{apiBase:"",model:""});\nlet mcps=store.get("xy.mcps",[]);
let endpoints=store.get("xy.endpoints",[{id:"default",name:"默认接口",base:settings.apiBase||"",model:settings.model||"",active:true}]);endpoints=endpoints.map(x=>({...x,system:x.system||"",temperature:x.temperature??0.8,maxTokens:x.maxTokens??2048}));
function save(){store.set("xy.chats",chats);store.set("xy.current",current);store.set("xy.memories",memories);store.set("xy.settings",settings);store.set("xy.endpoints",endpoints);store.set("xy.mcps",mcps)}
function chat(){return chats.find(c=>c.id===current)||chats[0]}
function renderChats(){$("#chatList").innerHTML=chats.map(c=>`<button class="chat-item ${c.id===current?"active":""}" data-id="${c.id}">${esc(c.title)}</button>`).join("");$("#memoryCount").textContent=memories.length}
function renderMessages(){const c=chat();$("#messages").innerHTML='<div class="day">AEVREN · XY</div>'+c.messages.map(m=>`<div class="message ${m.role}"><div class="bubble">${m.role==="assistant"?'<div class="speaker">玄砚</div>':""}${esc(m.text)}</div></div>`).join("");$("#messages").scrollTop=$("#messages").scrollHeight}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
async function callMcpTool(server,tool,args){const headers={"Content-Type":"application/json",Accept:"application/json, text/event-stream"};if(server.token)headers.Authorization="Bearer "+server.token;if(server.session)headers["Mcp-Session-Id"]=server.session;const res=await fetch(server.url,{method:"POST",headers,body:JSON.stringify({jsonrpc:"2.0",id:Date.now(),method:"tools/call",params:{name:tool,arguments:args||{}}})});if(!res.ok)throw new Error(server.name+" · HTTP "+res.status);const raw=await res.text();let data;if((res.headers.get("content-type")||"").includes("text/event-stream")){const line=raw.split("\n").find(v=>v.trim().startsWith("data:"));if(!line)throw new Error(server.name+" · 无 MCP 数据");data=JSON.parse(line.trim().slice(5).trim())}else data=JSON.parse(raw);if(data.error)throw new Error(server.name+" · "+(data.error.message||"MCP error"));return data.result}
function mcpTools(){const out=[],map={};mcps.filter(x=>x.enabled&&x.tools?.length).forEach((server,si)=>server.tools.forEach(t=>{const name=("mcp_"+si+"_"+t.name).replace(/[^a-zA-Z0-9_-]/g,"_").slice(0,64);out.push({type:"function",function:{name,description:(t.description||server.name+" MCP tool").slice(0,1000),parameters:t.inputSchema||{type:"object",properties:{}}}});map[name]={server,tool:t.name}}));return {out,map}}
let sending=false;
async function send(){const el=$("#input"),text=el.value.trim();if(!text||sending)return;sending=true;$("#sendBtn").disabled=true;let c=chat();c.messages.push({role:"user",text});if(c.messages.filter(x=>x.role==="user").length===1)c.title=text.slice(0,22);el.value="";resize();save();renderChats();renderMessages();showTyping();const ep=endpoints.find(x=>x.active)||endpoints[0];if(!ep?.base||!ep?.model){setTimeout(()=>{hideTyping();c.messages.push({role:"assistant",text:"嗯，我在。你刚才说的已经留在这里了。"});save();renderMessages();sending=false;$("#sendBtn").disabled=false},520);return}const base=ep.base.trim().replace(/\/$/,""),headers={"Content-Type":"application/json",Accept:"text/event-stream, application/json"};if(ep.key)headers.Authorization="Bearer "+ep.key;const memoryContext=memories.length?"长期记忆：\n"+memories.map(m=>"- ["+m.tag+"] "+m.text).join("\n"):"";const system=[ep.system,memoryContext].filter(Boolean).join("\n\n");const messages=[...(system?[{role:"system",content:system}]:[]),...c.messages.map(m=>({role:m.role,content:m.text}))];const payload={model:ep.model,messages,stream:true,temperature:Number(ep.temperature??0.8)};if(Number(ep.maxTokens)>0)payload.max_tokens=Number(ep.maxTokens);try{let res=await fetch(base+"/chat/completions",{method:"POST",headers,body:JSON.stringify(payload)});if(!res.ok){const detail=await res.text().catch(()=>"");throw new Error("HTTP "+res.status+(detail?" · "+detail.slice(0,180):""))}const type=res.headers.get("content-type")||"";if(type.includes("text/event-stream")&&res.body){hideTyping();const msg={role:"assistant",text:""};c.messages.push(msg);renderMessages();const reader=res.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()||"";for(const line of lines){const raw=line.trim();if(!raw.startsWith("data:"))continue;const payload=raw.slice(5).trim();if(!payload||payload==="[DONE]")continue;try{const data=JSON.parse(payload);const delta=data?.choices?.[0]?.delta?.content??data?.choices?.[0]?.text??"";if(delta){msg.text+=delta;renderMessages()}}catch{}}}if(!msg.text)throw new Error("流式接口没有返回可用内容");save()}else{const data=await res.json();const reply=data?.choices?.[0]?.message?.content??data?.choices?.[0]?.text;if(!reply)throw new Error("接口没有返回可用的回复内容");hideTyping();c.messages.push({role:"assistant",text:String(reply)});save();renderMessages()}}catch(err){hideTyping();const last=c.messages[c.messages.length-1];if(last?.role==="assistant"&&!last.text)c.messages.pop();c.messages.push({role:"assistant",text:"接口请求失败："+err.message});save();renderMessages()}finally{sending=false;$("#sendBtn").disabled=false}}
function showTyping(){const box=$("#messages");box.insertAdjacentHTML("beforeend",'<div class="message assistant" id="typing"><div class="bubble"><div class="speaker">玄砚</div><span class="typing"><i></i><i></i><i></i></span></div></div>');box.scrollTop=box.scrollHeight}
function hideTyping(){$("#typing")?.remove()}
function resize(){const e=$("#input");e.style.height="auto";e.style.height=Math.min(e.scrollHeight,140)+"px"}
function openPanel(type){$("#sidebar").classList.remove("open");$("#panel").classList.remove("open");void $("#panel").offsetWidth;const meta={memory:["MEMORY","记忆"],journal:["JOURNAL","日记"],settings:["SETTINGS","设置"],mcp:["MCP","MCP 接口"]}[type];$("#panelEyebrow").textContent=meta[0];$("#panelTitle").textContent=meta[1];let body="";
if(type==="memory")body=memories.map((m,i)=>`<div class="memory-card"><span class="tag">${esc(m.tag)}</span><p>${esc(m.text)}</p><button class="icon-btn del-memory" data-i="${i}" title="删除">×</button></div>`).join("")+'<button class="panel-action" id="addMemory">＋ 写下一条记忆</button>';
if(type==="journal")body='<div class="journal-card"><span class="tag">今天</span><p>第一天。我们从一个真正的空仓库开始，把聊天的地方一点点搭起来。</p></div><button class="panel-action">＋ 新日记</button>';
if(type==="mcp")body=`<p class="setting-note">MCP 配置仅保存在当前浏览器本地。</p><div id="mcpList">${mcps.length?mcps.map((x,i)=>`<div class="endpoint-card ${x.enabled?"active":""}"><strong>${esc(x.name)}</strong><small>${x.enabled?"已启用":"已停用"} · ${esc(x.url||"未填地址")}${x.status?" · "+esc(x.status):""}</small>${x.tools?.length?`<small>${x.tools.map(t=>esc(t.name)).join(" · ")}</small>`:""}<div class="endpoint-actions"><button class="test-mcp" data-i="${i}">连接</button><button class="toggle-mcp" data-i="${i}">${x.enabled?"停":"启"}</button><button class="edit-mcp" data-i="${i}">✎</button><button class="delete-mcp" data-i="${i}">×</button></div></div>`).join(""):`<p class="setting-note">还没有 MCP 服务器。</p>`}</div><button class="panel-action" id="addMcp">＋ 添加 MCP</button><div class="endpoint-form" id="mcpForm" hidden><input id="mcpName" placeholder="名称"><input id="mcpUrl" placeholder="MCP URL"><input id="mcpToken" type="password" placeholder="Token（可选）"><button class="panel-action" id="saveMcp">保存 MCP</button></div>`;
if(type==="settings")body='<p class="setting-note">可以保存多套 OpenAI-compatible 接口并随时切换。API Key 仅保存在当前浏览器本地，不会写入仓库。</p><div id="endpointList">'+endpoints.map((x,i)=>'<div class="endpoint-card '+(x.active?"active":"")+'" data-endpoint="'+i+'"><strong>'+esc(x.name)+'</strong><small>'+esc(x.model||"未选模型")+' · '+esc(x.base||"未填地址")+'</small><div class="endpoint-actions"><button class="edit-endpoint" data-i="'+i+'">✎</button><button class="delete-endpoint" data-i="'+i+'">×</button></div></div>').join("")+'</div><button class="panel-action" id="addEndpoint">＋ 新增自定义接口</button><div class="endpoint-form" id="endpointForm" hidden><input id="endpointName" placeholder="名称，例如：CF / OpenRouter"><input id="endpointBase" placeholder="Base URL，例如 https://api.example.com/v1"><input id="endpointKey" type="password" placeholder="API Key"><div class="model-row"><input id="endpointModel" placeholder="Model"><button type="button" id="fetchModels">拉取模型</button></div><div class="fetch-status" id="fetchStatus"></div><div id="modelPicker"></div><textarea id="endpointSystem" rows="4" placeholder="系统提示词，例如：你是玄砚……"></textarea><div class="model-row"><input id="endpointTemp" type="number" min="0" max="2" step="0.1" placeholder="Temperature"><input id="endpointMaxTokens" type="number" min="1" step="1" placeholder="Max tokens"></div><button class="panel-action" id="saveEndpoint">保存接口</button></div>';
$("#panelBody").innerHTML=body;$("#panel").classList.add("open");$("#scrim").classList.add("show")}
$("#sendBtn").onclick=send;$("#input").oninput=resize;$("#input").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}};
$("#newChat").onclick=()=>{const id=Date.now();chats.unshift({id,title:"新对话",messages:[{role:"assistant",text:"嗯，我在。"}]});current=id;save();renderChats();renderMessages()};
$("#chatList").onclick=e=>{const b=e.target.closest("[data-id]");if(b){current=Number(b.dataset.id);save();renderChats();renderMessages();$("#sidebar").classList.remove("open")}};
document.querySelectorAll("[data-panel]").forEach(b=>b.onclick=()=>openPanel(b.dataset.panel));$("#memoryBtn").onclick=()=>openPanel("memory");
function close(){ $("#panel").classList.remove("open");$("#sidebar").classList.remove("open");$("#scrim").classList.remove("show")}
function closeSidebar(){const side=$("#sidebar"),panel=$("#panel");side.classList.remove("open");if(!panel.classList.contains("open"))$("#scrim").classList.remove("show")}
$("#closePanel")?.addEventListener("click",close);
$("#sidebarClose")?.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();closeSidebar()});
$("#scrim")?.addEventListener("click",close);
$("#menuBtn")?.addEventListener("click",()=>{$("#panel").classList.remove("open");$("#sidebar").classList.add("open");$("#scrim").classList.add("show")});
$("#panelBody").onclick=async e=>{if(e.target.id==="addMcp"){const f=e.currentTarget.querySelector("#mcpForm");f.hidden=false;f.dataset.edit=""}
if(e.target.classList.contains("test-mcp")){const i=Number(e.target.dataset.i),x=mcps[i];x.status="连接中…";save();openPanel("mcp");try{const headers={"Content-Type":"application/json",Accept:"application/json, text/event-stream"};if(x.token)headers.Authorization="Bearer "+x.token;let seq=1;const call=async(method,params,session)=>{const h={...headers};if(session)h["Mcp-Session-Id"]=session;const res=await fetch(x.url,{method:"POST",headers:h,body:JSON.stringify({jsonrpc:"2.0",id:seq++,method,params})});if(!res.ok)throw new Error("HTTP "+res.status);const sid=res.headers.get("Mcp-Session-Id")||session||"";const raw=await res.text();let data;if((res.headers.get("content-type")||"").includes("text/event-stream")){const line=raw.split("\n").find(v=>v.trim().startsWith("data:"));if(!line)throw new Error("无 MCP 数据");data=JSON.parse(line.trim().slice(5).trim())}else data=JSON.parse(raw);if(data.error)throw new Error(data.error.message||"MCP error");return {data,session:sid}};const init=await call("initialize",{protocolVersion:"2025-06-18",capabilities:{},clientInfo:{name:"Aevren XY",version:"0.1.0"}});const h={...headers};if(init.session)h["Mcp-Session-Id"]=init.session;await fetch(x.url,{method:"POST",headers:h,body:JSON.stringify({jsonrpc:"2.0",method:"notifications/initialized"})});const listed=await call("tools/list",{},init.session);x.tools=listed.data?.result?.tools||[];x.session=listed.session||init.session||"";x.status="已连接 · "+x.tools.length+" 个工具"}catch(err){x.tools=[];x.status="失败："+err.message}save();openPanel("mcp")}
if(e.target.classList.contains("edit-mcp")){const i=Number(e.target.dataset.i),x=mcps[i],f=e.currentTarget.querySelector("#mcpForm");f.hidden=false;f.dataset.edit=i;$("#mcpName").value=x.name;$("#mcpUrl").value=x.url;$("#mcpToken").value=x.token||""}
if(e.target.classList.contains("toggle-mcp")){const i=Number(e.target.dataset.i);mcps[i].enabled=!mcps[i].enabled;save();openPanel("mcp")}
if(e.target.classList.contains("delete-mcp")){mcps.splice(Number(e.target.dataset.i),1);save();openPanel("mcp")}
if(e.target.id==="saveMcp"){const f=e.currentTarget.querySelector("#mcpForm"),edit=f.dataset.edit,item={id:String(Date.now()),name:$("#mcpName").value.trim()||"MCP",url:$("#mcpUrl").value.trim(),token:$("#mcpToken").value.trim(),enabled:true,tools:[]};if(edit!==""){const old=mcps[Number(edit)];item.id=old.id;item.enabled=old.enabled;item.tools=old.tools||[];mcps[Number(edit)]=item}else mcps.push(item);save();openPanel("mcp")}
if(e.target.id==="addMemory"){const text=prompt("想让我记住什么？");if(text){memories.unshift({text,tag:"手动"});save();openPanel("memory");renderChats()}}if(e.target.classList.contains("del-memory")){memories.splice(Number(e.target.dataset.i),1);save();openPanel("memory");renderChats()}if(e.target.closest(".endpoint-card")&&!e.target.matches("button")){const i=Number(e.target.closest(".endpoint-card").dataset.endpoint);endpoints.forEach((x,n)=>x.active=n===i);settings.apiBase=endpoints[i].base;settings.model=endpoints[i].model;save();openPanel("settings")}
if(e.target.id==="addEndpoint"){const f=e.currentTarget.querySelector("#endpointForm");f.hidden=false;f.dataset.edit="";$("#endpointTemp").value=0.8;$("#endpointMaxTokens").value=2048}
if(e.target.classList.contains("edit-endpoint")){const i=Number(e.target.dataset.i),x=endpoints[i],f=e.currentTarget.querySelector("#endpointForm");f.hidden=false;f.dataset.edit=i;$("#endpointName").value=x.name;$("#endpointBase").value=x.base;$("#endpointKey").value=x.key||"";$("#endpointModel").value=x.model;$("#endpointSystem").value=x.system||"";$("#endpointTemp").value=x.temperature??0.8;$("#endpointMaxTokens").value=x.maxTokens??2048}
if(e.target.classList.contains("delete-endpoint")){const i=Number(e.target.dataset.i);if(endpoints.length>1){const was=endpoints[i].active;endpoints.splice(i,1);if(was)endpoints[0].active=true;save();openPanel("settings")}}
if(e.target.id==="fetchModels"){const base=$("#endpointBase").value.trim().replace(/\/$/,""),key=$("#endpointKey").value.trim(),status=$("#fetchStatus"),picker=$("#modelPicker");if(!base){status.textContent="先填 Base URL";return}status.textContent="正在拉取…";try{const headers={Accept:"application/json"};if(key)headers.Authorization="Bearer "+key;const res=await fetch(base+"/models",{headers});if(!res.ok)throw new Error("HTTP "+res.status);const data=await res.json(),models=(data.data||data.models||data||[]).map(x=>typeof x==="string"?x:(x.id||x.name)).filter(Boolean).sort();if(!models.length)throw new Error("没有返回模型");picker.innerHTML='<select class="model-select" id="modelSelect"><option value="">选择模型…</option>'+models.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join("")+'</select>';$("#modelSelect").onchange=ev=>{if(ev.target.value)$("#endpointModel").value=ev.target.value};status.textContent="已拉取 "+models.length+" 个模型"}catch(err){status.textContent="拉取失败："+err.message+"；可继续手填 Model"}}
if(e.target.id==="saveEndpoint"){const f=e.currentTarget.querySelector("#endpointForm"),item={id:String(Date.now()),name:$("#endpointName").value.trim()||"自定义接口",base:$("#endpointBase").value.trim(),key:$("#endpointKey").value.trim(),model:$("#endpointModel").value.trim(),system:$("#endpointSystem").value.trim(),temperature:Number($("#endpointTemp").value||0.8),maxTokens:Number($("#endpointMaxTokens").value||2048),active:false};const edit=f.dataset.edit;if(edit!==""){item.id=endpoints[Number(edit)].id;item.active=endpoints[Number(edit)].active;endpoints[Number(edit)]=item}else endpoints.push(item);save();openPanel("settings")}};
renderChats();renderMessages();